apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-job2-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven
  template:
    metadata:
      labels:
        app: maven
    spec:
      containers:
      - name: k8s-job2
        image: mydocker1405/k8s-example:v1
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
      imagePullSecrets:
        - name: springboot1secret
